version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: ./.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: login/foodgram_backend:latest
    build: ../backend/
    env_file: ./.env
    volumes:
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - db

  frontend:
    image: login/foodgram_frontend:latest
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db

  # nginx:
  #   image: nginx:1.19.3
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #     - ../frontend/build:/usr/share/nginx/html/
  #     - ../docs/:/usr/share/nginx/html/api/docs/
  #     - static:/var/html/static/
  #     - media:/var/html/media/

  #   depends_on:
  #     - backend
  #     - frontend
  #   restart: always
