# Generated by Django 4.2.5 on 2023-09-28 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Название продукта"
                    ),
                ),
            ],
        ),
        migrations.RenameModel(
            old_name="Shops",
            new_name="Shop",
        ),
        migrations.RenameModel(
            old_name="Sales",
            new_name="Sale",
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.CharField(max_length=200, verbose_name="Группа товара "),
                ),
                (
                    "category",
                    models.CharField(max_length=200, verbose_name="Категория товара"),
                ),
                (
                    "subcategory",
                    models.CharField(
                        max_length=200, verbose_name="Подкатегория товара"
                    ),
                ),
                ("uom", models.SlugField(verbose_name="Маркер товара -на вес или шт")),
                (
                    "sku",
                    models.ForeignKey(
                        max_length=200,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                        verbose_name="Наименование товара ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ("id",),
            },
        ),
        migrations.AlterField(
            model_name="forecast",
            name="sku",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forecast",
                to="products.category",
                verbose_name="товар",
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="sku",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales",
                to="products.product",
                verbose_name="товар",
            ),
        ),
        migrations.DeleteModel(
            name="Categories",
        ),
    ]
