# Generated by Django 3.2.3 on 2023-10-09 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excel',
            options={'ordering': ('week',), 'verbose_name': 'Вывод статистики', 'verbose_name_plural': 'Вывод статистики'},
        ),
    ]
