# Generated by Django 4.2.5 on 2023-09-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "products",
            "0002_product_rename_shops_shop_rename_sales_sale_category_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="is_active",
            field=models.CharField(
                max_length=200, verbose_name="Флаг активного магазина"
            ),
        ),
    ]
