# Generated by Django 3.2.3 on 2023-10-06 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_forecast_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200, verbose_name='Категория товара')),
                ('subcategory', models.CharField(max_length=200, verbose_name='Подкатегория товара')),
                ('week', models.DateField()),
                ('sales_units', models.FloatField(verbose_name='Число проданных товаров без признака промо')),
                ('target', models.IntegerField()),
                ('difference', models.IntegerField()),
                ('wape', models.FloatField()),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.store', verbose_name='Магазин')),
            ],
        ),
    ]
