# Generated by Django 4.2.5 on 2023-09-28 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_alter_shop_format_alter_shop_loc_alter_shop_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="sku",
            field=models.CharField(max_length=200, verbose_name="Наименование товара "),
        ),
        migrations.AlterField(
            model_name="forecast",
            name="sku",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forecast",
                to="products.product",
                verbose_name="товар",
            ),
        ),
    ]
