# Generated by Django 4.2.5 on 2023-09-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_alter_sale_date_alter_sale_sku"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="date",
            field=models.DateField(max_length=200, verbose_name="Дата продажи товара"),
        ),
    ]
