# Generated by Django 4.2.5 on 2023-09-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_alter_sale_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата продажи товара"
            ),
        ),
    ]
