# Generated by Django 4.2.5 on 2023-09-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_alter_sale_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="sales_units",
            field=models.FloatField(
                verbose_name="Число проданных товаров без признака промо"
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="sales_units_promo",
            field=models.FloatField(
                verbose_name="Число проданных товаров c признаком промо"
            ),
        ),
    ]
