# Generated by Django 4.2.5 on 2023-09-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0011_alter_sale_store"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forecast",
            name="sku",
            field=models.CharField(max_length=200, verbose_name="товар"),
        ),
        migrations.AlterField(
            model_name="forecast",
            name="store",
            field=models.CharField(max_length=200, verbose_name="магазин"),
        ),
    ]
