# Generated by Django 4.2.5 on 2023-09-28 12:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0012_alter_forecast_sku_alter_forecast_store"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="forecast",
            name="forecast_date",
        ),
    ]
