# Generated by Django 3.2.3 on 2023-09-28 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_forecast_forecast_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
